Desktop/Projects/Helping-Hand-master/HelpingHand/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('register/', include('register.urls')),
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

Desktop/Projects/Helping-Hand-master/mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('create_event/', views.create_event, name='create_event'),
]

Desktop/Projects/Helping-Hand-master/register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    # path('', views.home_page, name='home_page'),
    path('', views.register, name="register"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('activate/<uidb64>/<token>/', views.user_verify, name="activate"),  
    path('ForgotPassword/', views.forgot_password, name="forgot_password"), 
    # path('ResetPassword/<uidb64>/<token>/', views.reset_password, name="reset_password"),  
    # path('ResetPasswordDone/', views.reset_password_done, name="reset_password_done"),  
 
]

Desktop/Projects/Helping-Hand-master/mainapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Event(models.Model):
    types = [('food','food'), ('clothes','clothes'), ('medical','medical'), ('others','others')]
    type_of_project = models.CharField(max_length=30, default='food', choices = types)
    event_organizer = models.CharField(max_length=100)
    event_name = models.CharField(max_length=100)
    event_date = models.DateField()
    place_name = models.CharField(max_length=350)
    event_type = models.CharField(max_length=50)
    lon = models.DecimalField(max_digits=9,decimal_places=6)
    lat = models.DecimalField(max_digits=9,decimal_places=6)
    description = models.TextField(max_length=500, null=True, blank=True)
    interested = models.ManyToManyField(User, related_name='interested', blank=True)

Desktop/Projects/Helping-Hand-master/mainapp/views.py
from django.shortcuts import render, redirect
from mainapp.models import Event
from django.contrib.auth.decorators import login_required

def home_page(request):
    id = request.GET.get('id')
    events = Event.objects.all()
    events_food = events.filter(event_type='Food')
    events_clothes = events.filter(event_type='Clothes')
    events_medical = events.filter(event_type='Medical')
    events_other = events.filter(event_type='Other')

    user = request.user if request.user.is_authenticated else None

    if user and id:
        event = Event.objects.filter(id=id).first()
        if event:
            if user in event.interested.all():
                event.interested.remove(user)
            else:
                event.interested.add(user)
            event.save()

    for event in events:
        event.is_interested = user in event.interested.all() if user else False

    context = {
        'events': events,
        'events_clothes': events_clothes,
        'events_food': events_food,
        'events_medical': events_medical,
        'events_other': events_other,
        'user': user,
    }

    return render(request, 'mainapp/home.html', context)

@login_required
def create_event(request):
    if request.method == 'POST':
        event_organizer = request.POST.get('event_organizer')
        event_name = request.POST.get('event_name')
        event_date = request.POST.get('event_date')
        description = request.POST.get('description')
        event_type = request.POST.get('event_type')
        place_name = request.POST.get('place_name')
        lat = request.POST.get('lat')
        lon = request.POST.get('lon')

        event = Event(
            event_organizer=event_organizer,
            event_name=event_name,
            event_date=event_date,
            description=description,
            place_name=place_name,
            event_type=event_type,
            lat=lat,
            lon=lon
        )
        event.save()
        return redirect('mainapp:home_page')

    return render(request, 'mainapp/create_event.html')

Desktop/Projects/Helping-Hand-master/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
  <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/v1.10.0/mapbox-gl.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}?rand=13062020" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <title>Helping Hand</title>
  <meta name="title" content="Helping Hand">
  <meta name="description"
    content="A social community platform for charity events organizers to connect and collaborate with each other">

  <!-- Open Graph / Facebook -->
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://helpinghand.pythonanywhere.com/">
  <meta property="og:title" content="Helping Hand">
  <meta property="og:description"
    content="A social community platform for charity events organizers to connect and collaborate with each other">
  <meta property="og:image" content="">

  <!-- Twitter -->
  <meta property="twitter:card" content="summary_large_image">
  <meta property="twitter:url" content="https://helpinghand.pythonanywhere.com/">
  <meta property="twitter:title" content="Helping Hand">
  <meta property="twitter:description"
    content="A social community platform for charity events organizers to connect and collaborate with each other">
  <meta property="twitter:image" content="">
</head>

<body>

  <nav class="navbar navbar-expand-md navbar-dark bg-dark" id="navbar">
    <a class="navbar-brand" href="{% url 'mainapp:home_page' %}">Helping Hand</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" onclick="removeChangeThemeBtn()" href="{% url 'mainapp:create_event' %}">Create Event</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="#">{{ user.first_name }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register:register' %}">Register</a>
        </li>
        {% endif %}
        <div id="chkDiv">
          <input type="checkbox" class="checkbox" onclick="changeTheme()" id="chk" />
          <label class="label" for="chk">
            <i class="fa fa-moon-o"></i>
            <i class="fa fa-sun-o"></i>
            <div class="ball"></div>
          </label>
        </div>
      </ul>
    </div>
  </nav>

  <div class="container-fluid">
    {% if message %}
    <div class="mt-3 alert alert-info alert-dismissible fade show" role="alert"> {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}
    {% block content %}
    {% endblock content %}
  </div>
</body>

</html>

Desktop/Projects/Helping-Hand-master/mainapp/templates/mainapp/create_event.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
{% include 'mainapp/script.html' %}
<div class="mt-3 container border" id="eventForm">
  <h3 class="mt-3"> Create an Event </h3>
  <hr id="hrLineCreateEvent" />
  <div class="row">
    <div class="px-4 col-12 col-md-6">
      <form method="post" action="{% url 'mainapp:create_event' %}" id="createEventForm">
        {% csrf_token %}
        <div class="form-group">
          <label for="event_name"> Event Name </label>
          <input type="text" class="form-control" name="event_name" id="event_name" required>
        </div>
        <div class="form-group">
          <label for="event_organizer"> Event Organizer </label>
          <input type="text" class="form-control" name="event_organizer" id="event_orgainizer" required>
        </div>
        <div class="row form-group">
          <div class="col-12 col-md-6">
            <label for="event_type"> Event Type </label>
            <select class="custom-select" name="event_type" id="event_type" required>
              <option selected value="Food">Food</option>
              <option value="Clothes">Clothes</option>
              <option value="Medical">Medical</option>
              <option value="Other">Other</option>
            </select>
          </div>
          <div class="col-12 col-md-6">
            <label for="event_date"> Event Date </label>
            <input type="date" class="form-control" name="event_date" id="event_date" required>
          </div>
        </div>
        <div class="form-group position-relative">
          <label> Event Location </label>
          <div id="geocoder" class="geocoder"></div>
        </div>
        <div class="form-group">
          <label for="description"> Event Details </label>
          <textarea class="form-control" name="description"></textarea>
        </div>
        <!-- Hidden Fields -->
        <!-- <div class="form-group">
					<label for=place_name"> Place Name </label> -->
        <input type="hidden" class="form-control" name="place_name" id="place_name" readonly>
        <!-- </div>
				<div class="row form-group">
					<div class="col-12 col-md-6">
						<label for="lon"> Latitude </label> -->
        <input type="hidden" class="form-control" name="lon" id="lon" readonly>
        <!-- </div>
					<div class="col-12 col-md-6">
						<label for=lat"> Longitude </label> -->
        <input type="hidden" class="form-control" name="lat" id="lat" readonly>
        <!-- </div>
				</div> -->
        <!-- /Hidden Fields -->
        <div class="form-group">
          <input class="btn btn-success" type="submit" />
        </div>
      </form>
    </div>

    <div class="col-12 col-md-6 position-relative">
      <div class="border" id="map"></div>
    </div>
  </div>
</div>
<script type="text/javascript" src="{% static 'js/update_theme_createEvent.js' %}"></script>
<script type="text/javascript" src="{% static 'js/create_map.js' %}"></script>
{% endblock content %}

Desktop/Projects/Helping-Hand-master/mainapp/templates/mainapp/home.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
{% include 'mainapp/script.html' %}
<div class="row" id="map-container">
  <div class="px-0 col-12 position-relative">
    <div id="home-map"></div>
  </div>
  <div class="py-2 col-12">
    <div class="row justify-content-center">
      <div class="col-auto">
          <span class="pointer food">●</span>Food
      </div>
      <div class="col-auto">
          <span class="pointer clothes">●</span>Clothes
      </div>
      <div class="col-auto">
          <span class="pointer medical">●</span>Medical
      </div>
      <div class="col-auto">
          <span class="pointer other">●</span>Other
      </div>
    </div>
  </div>
</div>

<!-- Cards Container -->
<div class="mt-5 container">
  <div class="row justify-content-between">
    <div class="col-auto">
        <h2> Upcoming Events </h2>
    </div>
    <div class="col-auto float-right">
      <button type="button" class="btn btn-primary" id="map-toggler" name="button">Hide Map</button>
    </div>
  </div>
  <hr id="hrLine"/>
  <div class="row">
    <div class="col-lg-12 d-flex justify-content-center">
      <ul id="portfolio-flters" class="list-group list-group-horizontal" style="background-color: black;">
        <li class="list-group-item active-filter" data-filter="all" onClick="setCards('all')">All</li>
        <li class="list-group-item" data-filter="food" onClick="setCards('food')">Food</li>
        <li class="list-group-item" data-filter="clothes" onClick="setCards('clothes')">Clothes</li>
        <li class="list-group-item" data-filter="medical" onClick="setCards('medical')">Medical</li>
        <li class="list-group-item" data-filter="other" onClick="setCards('other')">Others</li>
      </ul>
    </div>
  </div>
    <div class="row portfolio-container">
    {% for event in events %}
    <div class="pt-3 col-12 col-md-6 col-lg-4 portfolio-item {{ event.type_of_project|lower }}">
      <p id="eventType" style="display: none">{{ event.type_of_project|lower }}</p>
      <div class="card event-card eventBlock">
        <div class="card-header cardHeader">
          <h3> {{ event.event_name }} </h3>
          <div class="text-muted eventsInfo"> {{ event.event_date }} </div>
        </div>
        <div class="card-body cardBody">
          <div class="row justify-content-around">
            <div class="col-6">
              <h5> Items </h5>
              <p class="eventsInfo">{{ event.event_type }}</p>
            </div>
            <div class="col-6">
              <h5> Place </h5>
              <p class="eventsInfo"> {{ event.place_name }} </p>
            </div>
          </div>

          {% if user %}
            <div class="row justify-content-around">
              {% if event.is_interested %}
                <button class="btn btn-primary" onclick="window.location.href='?id={{ event.id }}'"><h5> Interested </h5></button>
              {% else %}
                <button class="btn btn-primary notInterestedBtn" style="background-color: #c5dff5; color: black;" onclick="window.location.href='?id={{ event.id }}'"><h5> Interested </h5></button>
              {% endif %}
            </div>
          {% endif %}

        </div>
        <div class="card-footer">
          <div class="row justify-content-between">
            <div class="col-auto">
              By: {{ event.event_organizer }}
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<!-- Add CSS for filter colors -->
<style>
  #portfolio-flters .list-group-item {
    background-color: #333; /* Default background color */
    color: #fff; /* Default text color */
    cursor: pointer;
  }

  #portfolio-flters .list-group-item.active-filter {
    background-color: #007bff; /* Active filter background color */
    color: #fff; /* Active filter text color */
  }

  #portfolio-flters .list-group-item:hover {
    background-color: #555; /* Background color on hover */
  }
</style>

<script>
  $(document).ready(function() {
    $('#map-toggler').click(function() {
      var $this = $(this);
      $('#map-container').toggle('blind', 1000);

      $this.toggleClass('hidden');
      if ($this.hasClass('hidden'))
        $this.html('Show on Map');
      else
        $this.html('Hide Map');
    });
  });
</script>

<script>
  mapboxgl.accessToken = 'pk.eyJ1IjoiamFudXNpaSIsImEiOiJjazl6d2IzdmYxMnJsM21wazB3a2llY2lwIn0.pLRf45aHIwdJ6dypoH0qSA';
  var map = new mapboxgl.Map({
    container: 'home-map', // Container ID
    style: 'mapbox://styles/mapbox/streets-v11', // Map style to use
    center: [76.9558, 11.0168], // Coimbatore coordinates [lng, lat]
    zoom: 10, // Starting zoom level
  });

  map.addControl(new mapboxgl.NavigationControl());

  // Function to create markers
  function createMarkers(data, markerClass) {
    data.features.forEach(function(marker) {
      var el = document.createElement('div');
      el.className = markerClass;

      new mapboxgl.Marker(el)
        .setLngLat(marker.geometry.coordinates)
        .setPopup(new mapboxgl.Popup({ offset: 25 })
          .setHTML('<h4>' + marker.properties.title + '</h4><p> by ' + marker.properties.description + '</p>'))
        .addTo(map);
    });
  }

  // Convert JSON data to JavaScript objects
  var eventsFood = JSON.parse(document.getElementById('events_food').textContent);
  var eventsClothes = JSON.parse(document.getElementById('events_clothes').textContent);
  var eventsMedical = JSON.parse(document.getElementById('events_medical').textContent);
  var eventsOther = JSON.parse(document.getElementById('events_other').textContent);

  // Create markers for each category
  createMarkers(eventsFood, 'marker-food');
  createMarkers(eventsClothes, 'marker-clothes');
  createMarkers(eventsMedical, 'marker-medical');
  createMarkers(eventsOther, 'marker-other');
</script>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const cardsList = Array.from(document.querySelector(".portfolio-container").children);

    function setCards(category) {
      console.log(`Filtering for category: ${category}`); // Debugging line
      cardsList.forEach(card => {
        // Check class names to debug
        console.log(`Card class names: ${card.className}`);
        const cardsCategory = card.classList.contains(category) || category === "all";
        console.log(`Card category: ${category}, Visible: ${cardsCategory}`); // Debugging line
        card.style.display = cardsCategory ? "block" : "none";
      });

      // Update the active class on filter buttons
      document.querySelectorAll('#portfolio-flters .list-group-item').forEach(item => {
        item.classList.remove('active-filter');
      });

      // Set the active class for the selected filter
      const activeItem = document.querySelector(`#portfolio-flters .list-group-item[data-filter="${category}"]`);
      if (activeItem) {
        activeItem.classList.add('active-filter');
      }
    }

    // Initialize display
    setCards('all');

    // Add event listeners for filter buttons
    document.querySelectorAll('#portfolio-flters .list-group-item').forEach(item => {
      item.addEventListener('click', function() {
        const category = this.getAttribute('data-filter');
        setCards(category);
      });
    });
  });
</script>

{% endblock content %}
``

Desktop/Projects/Helping-Hand-master/mainapp/templates/mainapp/script.html
<script src="https://api.mapbox.com/mapbox-gl-js/v1.10.0/mapbox-gl.js"></script>
<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.5.1/mapbox-gl-geocoder.min.js"></script>
<link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.5.1/mapbox-gl-geocoder.css" type="text/css"/>
<!-- Promise polyfill script required to use Mapbox GL Geocoder in IE 11 -->
<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>

<!-- Bootstrap Script -->
<script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
<!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script> -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<!-- TOGGLE EFFECT -->
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>